### ISSUE TITLE
新增模块后再次编辑模块保存时会有时间格式非法情况

### ISSUE THREAD

**Issue by yileye** [HttpRunner/HttpRunnerManager#10]
对模块进行修改时，在不修改提测时间的情况下，保存会出现时间格式非法，建议使用通用方法将格式进行格式化，并在前端进行时间格式校验

**Comment by yinquanwang** [comment]
前端校验这块后面会整体加上，目前页面这类型的错误是比较多，后面集中优化

**Comment by yinquanwang** [comment]
已修复
