### ISSUE TITLE
用例单个执行，前端报错

### ISSUE THREAD

**Issue by louqqson008** [HttpRunner/HttpRunnerManager#11]
群里有写过，这里再提下吧；   用例列表——》单个执行用例前端报错，无法执行
报错：
Uncaught TypeError: window.location.href is not a function
    at HTMLButtonElement.onclick ((index):264)
多个浏览器都不行

**Comment by yinquanwang** [comment]
已修复，目前单个执行都改成post请求，不会再出现这种兼容性问题
