### ISSUE TITLE
全局配置文件为什么不生效呢

### ISSUE THREAD

**Issue by q88535448** [HttpRunner/HttpRunnerManager#111]
按照要求添加了配置，关联了项目和模块，但是执行模块中的用例还是提示参数找不到，有人遇到过吗？

**Comment by wydydq** [comment]
遇到了这个错误，

**Comment by wydydq** [comment]
遇到了同样的问题，后来发现是用例没有引用到全局变量导致的，但是页面没法直接修改，修改数据库添加引用之后就好了：
<img width="795" alt="image" src="https://user-images.githubusercontent.com/8160205/49634476-c92b3f00-fa37-11e8-821f-a6a50c6912e3.png">
