### ISSUE TITLE
mysqlclient  

### ISSUE THREAD

**Issue by ggdkay** [HttpRunner/HttpRunnerManager#19]
[root@localhost ~]# pip install  mysqlclient
Collecting mysqlclient
  Using cached mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-SEwKwu/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SEwKwu/mysqlclient/

**Comment by yinquanwang** [comment]
这个是你自己本身电脑环境问题，不是代码问题哈

**Comment by guohongxing** [comment]
同样遇到这种问题

**Comment by mpc2008cn** [comment]
缺`default-libmysqlclient-dev`,查了2天终于装完了`requirements.txt`.
https://pypi.org/project/mysqlclient/1.3.13/
