### ISSUE TITLE
项目名中出现空格时，新增添加模块处失败

### ISSUE THREAD

**Issue by cong-long** [HttpRunner/HttpRunnerManager#20]
问题描述：

    新增的项目名中如果项目名里有空格，哪么无法给这个项目中添加模块，问题在于新增模块时发的POST请求中，传参belong_project的值不对，比如项目名为：TEST APP，那么添加模块的POST请求，belong_project值为TEST，即没有空格后面的东西。

解决办法：
       修改add_module.html页面第28行为下面，即使用双引号将pro_name包住即可解决该BUG。
                                         <option value="{{ foo.pro_name }}">{{ foo.pro_name }}</option>

**Comment by cong-long** [comment]
建议将所有的value赋值处，都用 "" 包起来，避免出现莫名奇妙的异常。

**Comment by yinquanwang** [comment]
多谢反馈！确实是有这个问题

**Comment by yileye** [comment]
关闭问题
