### ISSUE TITLE
无效的项目或模块信息没有显示出来

### ISSUE THREAD

**Issue by cong-long** [HttpRunner/HttpRunnerManager#21]
get_pager_info函数不应该先根据status，进行一次过滤，即：文件 pagination.py文件的88行代码：
obj = Model.objects.filter(status__exact=filter) 应该修改为
obj = Model.objects.filter()，否则模块和项目列表只会显示有效的。

**Comment by yinquanwang** [comment]
前端可以选择有效无效的

**Comment by cong-long** [comment]
哦哦，尴尬。。没注意到。
