### ISSUE TITLE
session失效引起的问题，新增配置页面，新增用例页面，用例、配置列表页面

### ISSUE THREAD

**Issue by chenchengyuan** [HttpRunner/HttpRunnerManager#22]
1、当session失效时，在新增配置页面、新增用例页面，点击提交操作时，不会跳转到登录页面，会弹出代码
2、当session失效时，在用例、配置列表页面，点击某一条时，不会跳转到登录页面，会弹出“session invalid”

![Uploading 选区_014.png…]()

**Comment by yileye** [comment]
第二个问题已经修复

**Comment by yinquanwang** [comment]
已修复
