### ISSUE TITLE
status_code校验填写的是200，实际保存到数据库中是'200'，导致校验出错

### ISSUE THREAD

**Issue by wangkangreg** [HttpRunner/HttpRunnerManager#3]
test_get3：httprunnermanager自己保存的数据
{'test': {'request': {'url': 'http://httpbin.org/get', 'method': 'GET'}, 'name': 'test_get3->test_module3->test_proj3', 'validate': [{'check': 'status_code', 'comparator': 'equals', 'expected': **'200'**}]}}

test_get4：手动到数据中中修改了expected的值
{'test': {'request': {'url': 'http://httpbin.org/get', 'method': 'GET'}, 'name': 'test_get4->test_module3->test_proj3', 'validate': [{'check': 'status_code', 'comparator': 'equals', 'expected': **200**}]}}

运行结果
![default](https://user-images.githubusercontent.com/1415013/36588434-052ca4d2-18c3-11e8-81ce-08e7b864542e.jpg)

**Comment by yinquanwang** [comment]
目前HttpRunnerManger数据都是字符串形式存储，所以造成了上述现象，后面会增加数据类型，一起修改掉，多谢反馈

**Comment by yinquanwang** [comment]
感谢支持，HttpRunnerManager目前所有数据都是以字符串形式存储，后期会区分数据类型，这个问题现在是会存在的

**Comment by yinquanwang** [comment]
你好，此bug已经修复，目前true，false会自动转换为boolean类型，1,1.23数字格式也会相应转换，null字符串会自动转换为null
