### ISSUE TITLE
麻烦请问下，json格式的，多个中括号组合的data，这个该怎么书写呢？

### ISSUE THREAD

**Issue by NASA2333** [HttpRunner/HttpRunnerManager#33]
当data由多个中括号的json组成时，这种情况下该怎么添加呢？比如下面这种
{"publicationType": "3",
  "newspaper_metadata": {
    "newspaperNameCn": "接口测试申请报纸数据-HLL",
    "newspaperType": "123",
    "newspaperCn": "123",
    "versionNumber": "132",
    "releaseDate": "2015-12-01",
    "releaseArea": "123",
    "issues": "111",
    "infoIntegrity": 1,
    "isTop": 1,
    "specifyPublisherType": "111",
    "specifyPublisherId": "1",
    "specifyPublisherName": "test",
    "fascicle": "111",
    "bookmaker": "111",
    "publishCountry": "123",
    "organizers": "123",
    "langId": 11,
    "competentOrg": "123",
    "keywords": "123",
    "domPubUnit": "123",
    "domEmailedCode": "123",
    "forPubUnit": "123",
    "forEmailedCode": "123",
    "priceType": "11.3,CNY",
 "codeType": "1",
    "colors": "1"}}

**Comment by yileye** [comment]
@NASA2333 我有时间看一下，或者你在群里提问一下

**Comment by yileye** [comment]
@NASA2333 你有样例数据嘛？我试一下

**Comment by NASA2333** [comment]
方便给个群号吗？到时候我私聊你接口吧，测试环境都在本地
