### ISSUE TITLE
[问题]访问地址是什么？

### ISSUE THREAD

**Issue by yileye** [HttpRunner/HttpRunnerManager#4]

**Comment by yinquanwang** [comment]
localhost:8000/api/index

**Comment by yileye** [comment]
`    except TypeError:
            result = fun(request)
        except (ImportError, AttributeError):    # 导入失败时，自定义404错误
            return HttpResponse('404 Not `Found')`
感觉这块的异常的处理设计的不太好，在访问的时候因为捕捉了异常，但是自定义的信息又不太明确，导致排查问题要花些时间

**Comment by yinquanwang** [comment]
访问地址：127.0.0.1:8000/api/index/，这块异常处理确实不合理，后面会优化

**Comment by lvorcool2016** [comment]
http://127.0.0.1:8000/api/index/ 访问时报404

**Comment by yinquanwang** [comment]
@lvorcool2016 ，你好应该是你部署的有问题，检查下时候有包没有安装呢？
