### ISSUE TITLE
点击·新增用例·报错

### ISSUE THREAD

**Issue by chenlisong** [HttpRunner/HttpRunnerManager#41]
用例列表中，点击新增用户报错。

信息如下。

Request Method: | GET
-- | --
http://192.168.37.99:8000/api/add_case/
2.0.3
FieldError
Cannot resolve keyword 'pro_name' into field. Choices are: create_time, dev_user, id, moduleinfo, other_desc, project_name, publish_app, responsible_name, simple_desc, test_user, update_time
/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py in add_fields, line 1706
/usr/bin/python
3.5.0
['/home/hrun/HttpRunnerManager',  '/usr/local/lib/python35.zip',  '/usr/local/lib/python3.5',  '/usr/local/lib/python3.5/plat-linux',  '/usr/local/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/site-packages',  '/usr/local/lib/python3.5/site-packages/setuptools-39.0.1-py3.5.egg',  '/usr/local/lib/python3.5/site-packages/pip-10.0.1-py3.5.egg',  '/home/hrun/HttpRunnerManager']
星期三, 25 四月 2018 19:59:27 +0800

**Comment by yinquanwang** [comment]
这几天正在改版，一直在主干开发，过几天就会恢复
