### ISSUE TITLE
新增用例，用例编辑页面，可选用例为空

### ISSUE THREAD

**Issue by chenchengyuan** [HttpRunner/HttpRunnerManager#47]
新增用例，用例编辑页面，可选用例为空，必须要在所属模块，先点一下“请选择”，再次点击某模块，可选用例才可以选到已有用例；还可以连续重复添加依赖用例
![_ _20180520010359](https://user-images.githubusercontent.com/29788128/40271028-3df1908a-5bca-11e8-99c5-138ac11f6d4d.png)
![_ _20180520010411](https://user-images.githubusercontent.com/29788128/40271029-3e37d36a-5bca-11e8-8233-6bb8b09ece4f.png)
![_ _20180520011325](https://user-images.githubusercontent.com/29788128/40271100-1154b4e8-5bcb-11e8-9475-2272fc75af93.png)

**Comment by yinquanwang** [comment]
用例是改变模块才会触发后台加载，是这样设计的，然后那个重复这个本身没有做限制，因为有其他同学有这个需求

**Comment by chenchengyuan** [comment]
改变模块才会触发，那把所属模块那默认设为“请选择”是不是更好，现在每次都要点两次才可以

**Comment by chenchengyuan** [comment]
新版本已修复
