### ISSUE TITLE
测试报告，左上角筛选，无效

### ISSUE THREAD

**Issue by chenchengyuan** [HttpRunner/HttpRunnerManager#55]
测试报告，左上角筛选，无效，选择Fail，筛选结果为空
![20180525_001](https://user-images.githubusercontent.com/29788128/40533178-6cc895e8-6034-11e8-82e6-c17597d3fbfe.png)

**Comment by yinquanwang** [comment]
确实是个bug，后期修复

**Comment by yinquanwang** [comment]
已修复
