### ISSUE TITLE
http://127.0.0.1:8000/api/index/访问时显示404 Not Found

### ISSUE THREAD

**Issue by lvorcool2016** [HttpRunner/HttpRunnerManager#6]
项目代码是昨天下载的，今天部署环境，配置数据库，最后启动结果出现这问题
详见截图

![2](https://user-images.githubusercontent.com/21286480/36716911-fbea4f48-1bd6-11e8-8dca-58d8a7f27648.jpg)

![1](https://user-images.githubusercontent.com/21286480/36716912-fc281fc6-1bd6-11e8-93af-47515dbe8b8f.jpg)

**Comment by yileye** [comment]
因为进行了异常捕捉，看不到真正的异常了信息了，建议暂时修改异常捕捉那块并打印全部的异常信息

**Comment by yileye** [comment]
在activator.py的25行进行修改

 except Exception as e:
        # 导入失败时，自定义404错误
        return HttpResponse(e)

**Comment by yinquanwang** [comment]
@lvorcool2016 ，能否加下qq远程帮你看下呢，也有小伙伴出现你这个问题，启动成功了，也报404，最后检查是缺少lib

**Comment by lvorcool2016** [comment]
@yinquanwang 我先處理下，問題出現在我沒安裝項目相關的庫依賴，謝謝 @yileye

**Comment by yinquanwang** [comment]
嗯嗯，应该是缺少yaml库 估计

**Comment by lvorcool2016** [comment]
現在就是缺少yaml庫，我在解決

**Comment by lvorcool2016** [comment]
解決了，python3.6安裝yaml的命令是pip install PyYAML。
運行沒問題了。
