### ISSUE TITLE
您好，想在报告中加一个响应结果的展示，但是有些地方不太清楚，能方便加下qq吗?2391148579，在此谢过了

### ISSUE THREAD

**Issue by githubnichen** [HttpRunner/HttpRunnerManager#7]

**Comment by githubnichen** [comment]
就是响应数据不知道怎么加到resultData中，求赐教啊

**Comment by yinquanwang** [comment]
@githubnichen 

> [你好，代码已经重构，目前所有成功或者失败用例均支持查询所有接口请求信息，以及异常时堆栈信息，请更新代码`[
![1](https://user-images.githubusercontent.com/32924136/36838763-05f38ac2-1d7b-11e8-9704-3c28a9cc2e25.png)
](url)

**Comment by githubnichen** [comment]
好的，谢谢，我试下
