### ISSUE TITLE
web端使用问题总结---期待修复

### ISSUE THREAD

**Issue by fxxangela** [HttpRunner/HttpRunnerManager#73]
1.当该用例包含一个前置依赖用例时，再次修改该用例，不能增加依赖用例，若要增加前置依赖用例，需要重新创建新的用例，方可增加。
2.不能夸模块依赖前置用例，比如：针对复用性高创建albumId的用例，也就是说每个模块都要新建albumid用例，增加了用例的重复性;
3.用例传参，json布尔值自动变换大写，只要再次修改该用例，就会报json错误，不修改不影响
4.目前不支持request请求方法patch，head，能否帮忙加进去
5.request请求时，能否加个file，可以上传文件。
6.测试用例能否支持导出json或yml文件，这样就可以与后台locusts性能测试时共用一个用例；

**Comment by yileye** [comment]
第二个问题已经修复

**Comment by yileye** [comment]
第四个和第五个可以考虑增加，但是要先把2.0的功能稳定下来，目前第六个也要纳入之后的排期中

**Comment by yileye** [comment]
第一个问题已经找到原因，是因为修改用例时前置条件选择的触发条件是需要选择项目，只有项目变化才会重新触发前置条件的选择，修改用例时，重新选择项目就可以在已有用例的基础上添加用例了，这个属于页面加载逻辑的一个bug，近期的版本就会修复，敬请关注

**Comment by yileye** [comment]
第三条能给一个复现的步骤或者数据吗

**Comment by yinquanwang** [comment]
问题3已修复
