### ISSUE TITLE
session中SESSION_COOKIE_AGE可以设置长一点的时间

### ISSUE THREAD

**Issue by nuanyang233** [HttpRunner/HttpRunnerManager#8]
SESSION_COOKIE_AGE的时间可以设置的长一点~

![qq 20180304200347](https://user-images.githubusercontent.com/28348152/36945331-2e0c5dfe-1fe7-11e8-8ece-a3483598771a.png)

**Comment by yinquanwang** [comment]
@nuanyang233   设置的10min应该不算短吧:
