### ISSUE TITLE
用例为json类型时，不支持HTTPrunner的函数调用

### ISSUE THREAD

**Issue by steven-xgt** [HttpRunner/HttpRunnerManager#96]
如题，当用例为data类型时，支持HTTPrunner的函数调用，但是，当json类型时就不支持了，如下截图：
![image](https://user-images.githubusercontent.com/29575784/44083791-8ed298d0-9fe7-11e8-904c-0f1ccf1d4161.png)

**Comment by yinquanwang** [comment]
试了httprunner用脚本方式支持么

**Comment by steven-xgt** [comment]
嗯，我这边直接有httprunner是支持的

**Comment by steven-xgt** [comment]
找到解决办法了，需要在variable那边引用函数

**Comment by yileye** [comment]
好的

**Comment by yileye** [comment]
我是了一下，是支持json数据的函数调用的，应该是没有问题的

**Comment by yileye** [comment]
可以关闭此问题
